version: "{build}"

image: Visual Studio 2015
platform:
  - x64

# Environment variables can be overridden in the Appveyor's build
# settings. A more secure password should be set there.
environment:
  winrm_user: appveyor
  winrm_pass: p@ssw0rd
  winrm_port: 5985
  KITCHEN_YAML: .kitchen.appveyor.yml

  matrix:
    - suite_name: "py3-windows"
      ruby_version: "24"
    - suite_name: "py2-windows"
      ruby_version: "24"

clone_depth: 15

install:
  - set APPVEYOR_RDP_PASSWORD=%winrm_pass%
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - ps: >-
      if ($env:winrm_user -ne "appveyor") {
        net user /add $env:winrm_user $env:winrm_pass;
        net localgroup administrators $env:winrm_user /add
      }
  - ps: $env:PATH="C:\Ruby$env:ruby_version\bin;$env:PATH"
  - ps: gem install bundler --quiet
  - ps: Invoke-WebRequest -Uri http://curl.haxx.se/ca/cacert.pem -OutFile c:\certs.pem
  - set SSL_CERT_FILE=c:\certs.pem
  - ps: Enable-PSRemoting â€“force
  - ps: winrm s winrm/config/client '@{TrustedHosts="*"}'
  - ps: winrm quickconfig
  - type Gemfile.appveyor > Gemfile

build_script:
  - bundle install

test_script:
  - ps: >-
     if ($env:DEBUG_BUILD -eq "yes") {
         bundle exec kitchen converge $env:suite_name -l debug | tee kitchen.run.log
     } else {
         bundle exec kitchen converge $env:suite_name | tee kitchen.run.log
     }

on_failure:
  - ps: ls ./*
  - bundle exec kitchen diagnose --all
  - winrm get winrm/config
  - winrm enumerate winrm/config/listener
  - ps: Get-ChildItem ".\\.kitchen\\logs\\kitchen.log" | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
  - ps: Get-ChildItem "kitchen.run.log" | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
